### ISSUE TITLE
Server Selection Screen Crash 

### ISSUE THREAD

**Issue by jc132333** [HitsparkInteractive/NinOnline#26]
This  is what it loos like in the (data files/logs/errors) file. 

14/08/2021 12:43:13 PM
The following error occured 'The remote name could not be resolved: 'ipv4.icanhazip.com'' at '   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at client.modAuth.GetIPAddress()
   at client.modClientTCP.nqT5AeNAqg3KhiDMt8eQ()
   at client.modClientTCP.ConnectToServer()
   at client.modAuth.WJOLT8fmuqxeLeaERoP()
   at client.modAuth.ServerSelect(Int32 ServerSelection)
   at client.modInterfaceEvents.hABfxaNATOJmU8Bl8l5A(Int32 ServerSelection)
   at client.modInterfaceEvents.btnSSSelect_MouseUp(Int32 CurWindow, Int32 CurControl, Int32 Var, Int32 ExtraVar)
   at client.modInterfaceEvents.S0Xqf3NAIA8Tm6TnZ3th(Object , Int32 CurWindow, Int32 CurControl, Int32 KeyAscii, Int32 ExtraVar)
   at client.modInterfaceEvents.HandleGuiMouse(entStates entState)
   at client.modInterfaceEvents.xhL8dpNAC8oqJEgBViNY(entStates entState)
   at client.modInterfaceEvents.HandleMouseInput()
   at client.modGameLogic.B6kZFSNsjBtDoHytwwLp()
   at client.modGameLogic.MainLoop()'.
[Info]
This is an Unhandled Exception! Please Report this!  

![Untitled](https://user-images.githubusercontent.com/88920176/129434986-c4346e5c-f2a1-4885-ab39-d534419cf9a6.png)

**Comment by RorySoh** [comment]
Hi there, is your computer/network able to access this website?
ipv4.icanhazip.com

It should return your own IP in text

**Comment by jc132333** [comment]
Good Day, It works on my phone but not on the pc.

**Comment by jc132333** [comment]
> Hi there, is your computer/network able to access this website?
> ipv4.icanhazip.com
> 
> It should return your own IP in text

Good Day, It works on my phone but not on the computer.
I can access the website through my phone using the same network but can't with computer.

**Comment by RorySoh** [comment]
Alright, we'll see how we can more reliably get that data in the next update. Should be fixed in a day or two. Thank you!

**Comment by jc132333** [comment]
> Alright, we'll see how we can more reliably get that data in the next update. Should be fixed in a day or two. Thank you!

Thank you for your time.

**Comment by jc132333** [comment]
> Alright, we'll see how we can more reliably get that data in the next update. Should be fixed in a day or two. Thank you!

Sorry for the disturbance but,

17/08/2021 7:21:44 PM
The following error occured 'The remote name could not be resolved: 'api.ipify.org'' at '   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at client.modAuth.mv69VToU9gx3i16IWCF(Object , Object )
   at client.modAuth.GetIPAddress() in D:\NinOnlineSrc\Core\ninonline-c-client\modAuth.cs:line 35
   at client.modClientTCP.ConnectToServer() in D:\NinOnlineSrc\Core\ninonline-c-client\modClientTCP.cs:line 80
   at client.modAuth.M7RO5KrNniMFuYB4eKa()
   at client.modAuth.ServerSelect(Int32 ServerSelection) in D:\NinOnlineSrc\Core\ninonline-c-client\modAuth.cs:line 268
   at client.modInterfaceEvents.btnSSSelect_MouseUp(Int32 CurWindow, Int32 CurControl, Int32 Var, Int32 ExtraVar) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 564
   at client.modInterfaceEvents.HandleGuiMouse(entStates entState) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 371
   at client.modInterfaceEvents.HandleMouseInput() in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 139
   at client.modGameLogic.aMZMdawYQm2UXcWZYWf2()
   at client.modGameLogic.MainLoop() in D:\NinOnlineSrc\Core\ninonline-c-client\modGameLogic.cs:line 4296'.
[Info]
This is an Unhandled Exception! Please Report this!

The text change but I still can't open the IP issue while I can with my phone, edit: when i cleared my DNS for all devices i cant access anymore

**Comment by jc132333** [comment]
> Alright, we'll see how we can more reliably get that data in the next update. Should be fixed in a day or two. Thank you!

I don't think it's a new error from the above, it just says "This site can’t be reached" when I type or go to api.ipify.org. Is there a setting to turn off or on in the windows feature?
