### ISSUE TITLE
Unable to launch game

### ISSUE THREAD

**Issue by Gaara1024** [HitsparkInteractive/NinOnline#29]
My game crashes when I select a server. I have tried different characters and it happens to both.

Launch the game, select login, selecting my character to log in, server select comes up.

1.I have tried to select the server by clicking on it
2.By pressing enter

## Observed result

Same result

## More details

**Affected Client Version:** 

Inochi Client

I first noticed it today, after the most recent update

## Error Logs

N/A

PASTE HERE

</details>

**Comment by Gaara1024** [comment]
Also, losing out on time to complete the event is kind of unfair. I would love to see a slight extension or I let the quest part that you are on stick around after the event but not progress. For example, I hit level 40 before the end of the event I can complete the level 50 quest when I hit 50 but I do not get the level 60 quest. I think that would be a fair compromise.

**Comment by RorySoh** [comment]
Hi there,

Can you check your log files as per the instructions of the bug report template?
Has this just started today?

**Comment by RorySoh** [comment]
Can you see if you can access this site?
https://api.ipify.org

Does it return an IP for you?

**Comment by Gaara1024** [comment]
it did just start today. It does not return and IP address when I try to browse to it. I tried to ping it and got nothing.

Flushed my DNS just now and couldn't ping it again.

**Comment by Gaara1024** [comment]
I tried to disconnect from the VPN and tested it again and still nothing. 

I do have the latest security patches from windows 10.

How do I check the error logs?

**Comment by Gaara1024** [comment]
Also, I'm an ERP (Enterprise Resource Planning) developer for a steel company. Not your normal user, if need be I have tools at my disposal like wire shark and whatnot. Let me know what you want me to do and I can do it.

**Comment by jc132333** [comment]
I may also "still" have the same problem as him. I can access it with my phone but not my computer, so are there settings to be turned off or on in gathering IP? maybe disabling some sites and such or other things?
Edit: when i cleared my DNS for every device i use, not one of them can access it anymore 

This is for the launcher logs in my case
########## Tue Aug 17 19:53:51 2021 - Log start
[INFO]     Tue Aug 17 19:53:51 2021 - Successful lock on  ".lock"
[INFO]     Tue Aug 17 19:53:51 2021 - Updating the patcher
[INFO]     Tue Aug 17 19:53:51 2021 - Getting the latest app version for app  "9e04617386ce3791f5ad8ff39be86d9f"
[INFO]     Tue Aug 17 19:53:51 2021 - Executing GET  "1/apps/9e04617386ce3791f5ad8ff39be86d9f/versions/latest/id"
[INFO]     Tue Aug 17 19:53:51 2021 - Downloading from  "https://api2.patchkit.net/1/apps/9e04617386ce3791f5ad8ff39be86d9f/versions/latest/id"  with timeout  10000
[INFO]     Tue Aug 17 19:53:52 2021 - Checking whether patcher is installed.
[INFO]     Tue Aug 17 19:53:52 2021 - Installation found. Checking version compatibility.
[INFO]     Tue Aug 17 19:53:52 2021 - Reading version info of installed patcher.
[INFO]     Tue Aug 17 19:53:52 2021 - Parsing version info to number -  "63"
[INFO]     Tue Aug 17 19:53:52 2021 - Local patcher id -  "04617386ce3791f5ad8ff39be86d"
[INFO]     Tue Aug 17 19:53:52 2021 - Local version - 63
[INFO]     Tue Aug 17 19:53:52 2021 - Latest version is already installed
[INFO]     Tue Aug 17 19:53:52 2021 - Starting patcher.
[INFO]     Tue Aug 17 19:53:52 2021 - Reading patcher manifest.
[DEBUG]    Tue Aug 17 19:53:52 2021 - Preparing execute target:  "C:/Program Files (x86)/Nin Online/patcher/Patcher.exe"  with arguments:  ("--installdir", "C:/Program Files (x86)/Nin Online/app", "--lockfile", "C:/Program Files (x86)/Nin Online/.lock", "--secret", "N/+T/zX/kf+d/zv/m/+X/zX/Of85/zf/O/+d/5v/Nf+d/zv/mf+N/4//m/8z/5X/Of81/5H/kf87/zf/nf+f/w==", "--online")
[INFO]     Tue Aug 17 19:53:52 2021 - Unlocking the lock file.
[INFO]     Tue Aug 17 19:53:52 2021 - Launcher has finished successfully
[INFO]     Tue Aug 17 19:53:52 2021 - Close window request.
[INFO]     Tue Aug 17 19:53:52 2021 - Allowing the window to be closed.


And the error logs
17/08/2021 8:02:25 PM
The following error occured 'The remote name could not be resolved: 'api.ipify.org'' at '   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at client.modAuth.mv69VToU9gx3i16IWCF(Object , Object )
   at client.modAuth.GetIPAddress() in D:\NinOnlineSrc\Core\ninonline-c-client\modAuth.cs:line 35
   at client.modClientTCP.ConnectToServer() in D:\NinOnlineSrc\Core\ninonline-c-client\modClientTCP.cs:line 80
   at client.modAuth.M7RO5KrNniMFuYB4eKa()
   at client.modAuth.ServerSelect(Int32 ServerSelection) in D:\NinOnlineSrc\Core\ninonline-c-client\modAuth.cs:line 268
   at client.modInterfaceEvents.btnSSSelect_MouseUp(Int32 CurWindow, Int32 CurControl, Int32 Var, Int32 ExtraVar) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 564
   at client.modInterfaceEvents.HandleGuiMouse(entStates entState) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 371
   at client.modInterfaceEvents.HandleMouseInput() in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 139
   at client.modGameLogic.aMZMdawYQm2UXcWZYWf2()
   at client.modGameLogic.MainLoop() in D:\NinOnlineSrc\Core\ninonline-c-client\modGameLogic.cs:line 4296'.
[Info]
This is an Unhandled Exception! Please Report this!

**Comment by Gaara1024** [comment]
How did you pull your error logs? Via the event viewer?

**Comment by jc132333** [comment]
Nin online folder then, launcher log or logs/bin file

**Comment by jc132333** [comment]
data files/logs/errors

Playble now thx

**Comment by Gaara1024** [comment]
8/17/2021 7:57:42 PM
The following error occured 'The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.' at '   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at client.modAuth.E3PvmMlXPNkJYZyOCo3(Object , Object )
   at client.modAuth.GetIPAddress() in D:\NinOnlineSrc\Core\ninonline-c-client\modAuth.cs:line 35
   at client.modClientTCP.ConnectToServer() in D:\NinOnlineSrc\Core\ninonline-c-client\modClientTCP.cs:line 80
   at client.modAuth.ROXrMcXAYdRGDvftKQP()
   at client.modAuth.ServerSelect(Int32 ServerSelection) in D:\NinOnlineSrc\Core\ninonline-c-client\modAuth.cs:line 268
   at client.modInterfaceEvents.btnSSSelect_MouseUp(Int32 CurWindow, Int32 CurControl, Int32 Var, Int32 ExtraVar) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 564
   at client.modInterfaceEvents.UM85kidF11ukXG0qxKVE(Object , Int32 CurWindow, Int32 CurControl, Int32 KeyAscii, Int32 ExtraVar)
   at client.modInterfaceEvents.HandleGuiMouse(entStates entState) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 371
   at client.modInterfaceEvents.ktJPsvdFa6PlyeQXBx3b(entStates entState)
   at client.modInterfaceEvents.HandleMouseInput() in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 139
   at client.modGameLogic.PwM1PYdJolQBp3f307rY()
   at client.modGameLogic.MainLoop() in D:\NinOnlineSrc\Core\ninonline-c-client\modGameLogic.cs:line 4296'.
[Info]
This is an Unhandled Exception! Please Report this!

8/17/2021 10:09:51 PM
The following error occured 'The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.' at '   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at client.modAuth.E3PvmMlXPNkJYZyOCo3(Object , Object )
   at client.modAuth.GetIPAddress() in D:\NinOnlineSrc\Core\ninonline-c-client\modAuth.cs:line 35
   at client.modClientTCP.ConnectToServer() in D:\NinOnlineSrc\Core\ninonline-c-client\modClientTCP.cs:line 80
   at client.modAuth.ROXrMcXAYdRGDvftKQP()
   at client.modAuth.ServerSelect(Int32 ServerSelection) in D:\NinOnlineSrc\Core\ninonline-c-client\modAuth.cs:line 268
   at client.modInterfaceEvents.btnSSSelect_MouseUp(Int32 CurWindow, Int32 CurControl, Int32 Var, Int32 ExtraVar) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 564
   at client.modInterfaceEvents.UM85kidF11ukXG0qxKVE(Object , Int32 CurWindow, Int32 CurControl, Int32 KeyAscii, Int32 ExtraVar)
   at client.modInterfaceEvents.HandleGuiMouse(entStates entState) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 371
   at client.modInterfaceEvents.ktJPsvdFa6PlyeQXBx3b(entStates entState)
   at client.modInterfaceEvents.HandleMouseInput() in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 139
   at client.modGameLogic.PwM1PYdJolQBp3f307rY()
   at client.modGameLogic.MainLoop() in D:\NinOnlineSrc\Core\ninonline-c-client\modGameLogic.cs:line 4296'.
[Info]
This is an Unhandled Exception! Please Report this!

**Comment by Gaara1024** [comment]
awesome, thanks!

**Comment by Saltydiceg** [comment]
i got the same error too. i am also having trouble figuring out whats wrong for days now.  at first i thought my computer is busted but after seeing the logs of others i also has the same error not sure what to do.

Edit: Sorry i feel like an idiot but here hope this helps. but this guide work for me. just change your DNS to 8.8.8.8 and 8.8.4.4

Link: https://nestify.io/blog/the-easy-guide-to-fix-dns_probe_finished_nxdomain-error/


17/08/2021 9:54:12 pm
The following error occured 'The remote name could not be resolved: 'api.ipify.org'' at '   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at client.modAuth.mv69VToU9gx3i16IWCF(Object , Object )
   at client.modAuth.GetIPAddress() in D:\NinOnlineSrc\Core\ninonline-c-client\modAuth.cs:line 35
   at client.modClientTCP.ConnectToServer() in D:\NinOnlineSrc\Core\ninonline-c-client\modClientTCP.cs:line 80
   at client.modAuth.M7RO5KrNniMFuYB4eKa()
   at client.modAuth.ServerSelect(Int32 ServerSelection) in D:\NinOnlineSrc\Core\ninonline-c-client\modAuth.cs:line 268
   at client.modInterfaceEvents.btnSSSelect_MouseUp(Int32 CurWindow, Int32 CurControl, Int32 Var, Int32 ExtraVar) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 564
   at client.modInterfaceEvents.HandleGuiMouse(entStates entState) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 371
   at client.modInterfaceEvents.HandleMouseInput() in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 139
   at client.modGameLogic.aMZMdawYQm2UXcWZYWf2()
   at client.modGameLogic.MainLoop() in D:\NinOnlineSrc\Core\ninonline-c-client\modGameLogic.cs:line 4296'.
[Info]
This is an Unhandled Exception! Please Report this!

**Comment by RorySoh** [comment]
I think we fixed this in the latest update.
But yeah changing your DNS should help!
