### ISSUE TITLE
Can't login, Pressing login is insta crash

### ISSUE THREAD

**Issue by Memzky** [HitsparkInteractive/NinOnline#41]
## Problem description
When I press login button, It instant crashes

## Steps to reproduce issue
Launch the client
Press Play
Then Press Login Button

## More details

**Affected Client Version:** INOCHI CLIENT

**First noticed:** 17/08/2021

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by ryanara3** [comment]
My friend (Hadashah) is also having this issue. I got this error report after trying a few times:
![Discord_rxHnLuBqVz](https://user-images.githubusercontent.com/20247515/130353746-8358612e-e7da-4350-bc86-08009af46317.png)

This is her relevant error log:

8/22/2021 6:23:55 AM
The following error occured 'The system cannot find the file specified' at '   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at client.modAuth.o4v1woKzxG6XHiagQ7g(Object )
   at client.modAuth.ConnectToOAuth() in D:\NinOnlineSrc\Core\ninonline-c-client\modAuth.cs:line 157
   at client.modInterfaceEvents.aivYFCqwXwY819HE8jNd()
   at client.modInterfaceEvents.btnMMenuLogin_MouseUp(Int32 CurWindow, Int32 CurControl, Int32 KeyAscii, Int32 ExtraVar) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 445
   at client.modInterfaceEvents.FRAXbjqwMKT4XBnPPnxk(Object , Int32 CurWindow, Int32 CurControl, Int32 KeyAscii, Int32 ExtraVar)
   at client.modInterfaceEvents.HandleGuiMouse(entStates entState) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 371
   at client.modInterfaceEvents.nnSjBMqwioYV9boPI0aK(entStates entState)
   at client.modInterfaceEvents.HandleMouseInput() in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 139
   at client.modGameLogic.M9aEL0qWHynTR7urjl2P()
   at client.modGameLogic.MainLoop() in D:\NinOnlineSrc\Core\ninonline-c-client\modGameLogic.cs:line 4301'.
[Info]
This is an Unhandled Exception! Please Report this!

8/22/2021 6:30:08 AM
The following error occured 'The system cannot find the file specified' at '   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at client.modAuth.o4v1woKzxG6XHiagQ7g(Object )
   at client.modAuth.ConnectToOAuth() in D:\NinOnlineSrc\Core\ninonline-c-client\modAuth.cs:line 157
   at client.modInterfaceEvents.aivYFCqwXwY819HE8jNd()
   at client.modInterfaceEvents.btnMMenuLogin_MouseUp(Int32 CurWindow, Int32 CurControl, Int32 KeyAscii, Int32 ExtraVar) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 445
   at client.modInterfaceEvents.FRAXbjqwMKT4XBnPPnxk(Object , Int32 CurWindow, Int32 CurControl, Int32 KeyAscii, Int32 ExtraVar)
   at client.modInterfaceEvents.HandleGuiMouse(entStates entState) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 371
   at client.modInterfaceEvents.nnSjBMqwioYV9boPI0aK(entStates entState)
   at client.modInterfaceEvents.HandleMouseInput() in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 139
   at client.modGameLogic.M9aEL0qWHynTR7urjl2P()
   at client.modGameLogic.MainLoop() in D:\NinOnlineSrc\Core\ninonline-c-client\modGameLogic.cs:line 4301'.
[Info]
This is an Unhandled Exception! Please Report this!

**Comment by RorySoh** [comment]
> My friend (Hadashah) is also having this issue. I got this error report after trying a few times:
> ![Discord_rxHnLuBqVz](https://user-images.githubusercontent.com/20247515/130353746-8358612e-e7da-4350-bc86-08009af46317.png)
> 
> This is her relevant error log:
> 
> 8/22/2021 6:23:55 AM
> The following error occured 'The system cannot find the file specified' at ' at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
> at client.modAuth.o4v1woKzxG6XHiagQ7g(Object )
> at client.modAuth.ConnectToOAuth() in D:\NinOnlineSrc\Core\ninonline-c-client\modAuth.cs:line 157
> at client.modInterfaceEvents.aivYFCqwXwY819HE8jNd()
> at client.modInterfaceEvents.btnMMenuLogin_MouseUp(Int32 CurWindow, Int32 CurControl, Int32 KeyAscii, Int32 ExtraVar) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 445
> at client.modInterfaceEvents.FRAXbjqwMKT4XBnPPnxk(Object , Int32 CurWindow, Int32 CurControl, Int32 KeyAscii, Int32 ExtraVar)
> at client.modInterfaceEvents.HandleGuiMouse(entStates entState) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 371
> at client.modInterfaceEvents.nnSjBMqwioYV9boPI0aK(entStates entState)
> at client.modInterfaceEvents.HandleMouseInput() in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 139
> at client.modGameLogic.M9aEL0qWHynTR7urjl2P()
> at client.modGameLogic.MainLoop() in D:\NinOnlineSrc\Core\ninonline-c-client\modGameLogic.cs:line 4301'.
> [Info]
> This is an Unhandled Exception! Please Report this!
> 
> 8/22/2021 6:30:08 AM
> The following error occured 'The system cannot find the file specified' at ' at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
> at client.modAuth.o4v1woKzxG6XHiagQ7g(Object )
> at client.modAuth.ConnectToOAuth() in D:\NinOnlineSrc\Core\ninonline-c-client\modAuth.cs:line 157
> at client.modInterfaceEvents.aivYFCqwXwY819HE8jNd()
> at client.modInterfaceEvents.btnMMenuLogin_MouseUp(Int32 CurWindow, Int32 CurControl, Int32 KeyAscii, Int32 ExtraVar) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 445
> at client.modInterfaceEvents.FRAXbjqwMKT4XBnPPnxk(Object , Int32 CurWindow, Int32 CurControl, Int32 KeyAscii, Int32 ExtraVar)
> at client.modInterfaceEvents.HandleGuiMouse(entStates entState) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 371
> at client.modInterfaceEvents.nnSjBMqwioYV9boPI0aK(entStates entState)
> at client.modInterfaceEvents.HandleMouseInput() in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 139
> at client.modGameLogic.M9aEL0qWHynTR7urjl2P()
> at client.modGameLogic.MainLoop() in D:\NinOnlineSrc\Core\ninonline-c-client\modGameLogic.cs:line 4301'.
> [Info]
> This is an Unhandled Exception! Please Report this!

This is a separate issue.
The main issue does not have enough information.
Closing.
