### ISSUE TITLE
Nin crashes when pressing login.

### ISSUE THREAD

**Issue by Seitenchi** [HitsparkInteractive/NinOnline#57]
## Steps to reproduce issue

1. install nin online, 
2. start nin, press login
3. window disappears

## Observed result

the window is gone but the hitspark.exe is still running. Also the error log happens.

## Expected result

username and password screen to appear

## More details

**Affected Client Version:** 

**First noticed:**   Yesterday I tried to update nin and login but that didn't go so well, so I reinstalled but that did not work either. Added every executable in the program to my firewall exceptions, and attempted to download fresh nin and install with windows defender firewall and antivirus turned off. The same thing happens tho.

## Error Logs

<details><summary>View details</summary>

8/26/2021 3:23:52 AM
The following error occured 'The system cannot find the file specified' at '   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at client.modAuth.ConnectToOAuth() in D:\NinOnlineSrc\Core\ninonline-c-client\modAuth.cs:line 157
   at client.modInterfaceEvents.l07bqLWwWrnl0YryKQIc()
   at client.modInterfaceEvents.btnMMenuLogin_MouseUp(Int32 CurWindow, Int32 CurControl, Int32 KeyAscii, Int32 ExtraVar) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 445
   at client.modInterfaceEvents.vN5QsZWhzy4cu4w2sTAI(Object , Int32 CurWindow, Int32 CurControl, Int32 KeyAscii, Int32 ExtraVar)
   at client.modInterfaceEvents.HandleGuiMouse(entStates entState) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 371
   at client.modInterfaceEvents.qUsWEIWhIO6wfB4S4fEb(entStates entState)
   at client.modInterfaceEvents.HandleMouseInput() in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 139
   at client.modGameLogic.ayeYkjWy9e4qDCEDvVsp()
   at client.modGameLogic.MainLoop() in D:\NinOnlineSrc\Core\ninonline-c-client\modGameLogic.cs:line 4204'.
[Info]
This is an Unhandled Exception! Please Report this!

8/28/2021 1:38:52 PM
The following error occured 'The system cannot find the file specified' at '   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at client.modAuth.ConnectToOAuth() in D:\NinOnlineSrc\Core\ninonline-c-client\modAuth.cs:line 157
   at client.modInterfaceEvents.l07bqLWwWrnl0YryKQIc()
   at client.modInterfaceEvents.btnMMenuLogin_MouseUp(Int32 CurWindow, Int32 CurControl, Int32 KeyAscii, Int32 ExtraVar) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 445
   at client.modInterfaceEvents.vN5QsZWhzy4cu4w2sTAI(Object , Int32 CurWindow, Int32 CurControl, Int32 KeyAscii, Int32 ExtraVar)
   at client.modInterfaceEvents.HandleGuiMouse(entStates entState) in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 371
   at client.modInterfaceEvents.qUsWEIWhIO6wfB4S4fEb(entStates entState)
   at client.modInterfaceEvents.HandleMouseInput() in D:\NinOnlineSrc\Core\ninonline-c-client\modInterfaceEvents.cs:line 139
   at client.modGameLogic.ayeYkjWy9e4qDCEDvVsp()
   at client.modGameLogic.MainLoop() in D:\NinOnlineSrc\Core\ninonline-c-client\modGameLogic.cs:line 4204'.
[Info]
This is an Unhandled Exception! Please Report this!
It's possible this is connected, maybe the game is reading a click on the login button as a close action. 
from launcher-log.txt 
########## Tue Aug 31 21:23:43 2021 - Log start
[INFO]     Tue Aug 31 21:23:43 2021 - Successful lock on  ".lock"
[INFO]     Tue Aug 31 21:23:43 2021 - Updating the patcher
[INFO]     Tue Aug 31 21:23:43 2021 - Getting the latest app version for app  "ea9f3a9c9489b3a6b4d929b5e213b293"
[INFO]     Tue Aug 31 21:23:43 2021 - Executing GET  "1/apps/ea9f3a9c9489b3a6b4d929b5e213b293/versions/latest/id"
[INFO]     Tue Aug 31 21:23:43 2021 - Downloading from  "https://api2.patchkit.net/1/apps/ea9f3a9c9489b3a6b4d929b5e213b293/versions/latest/id"  with timeout  10000
[INFO]     Tue Aug 31 21:23:43 2021 - Checking whether patcher is installed.
[INFO]     Tue Aug 31 21:23:43 2021 - Installation found. Checking version compatibility.
[INFO]     Tue Aug 31 21:23:43 2021 - Reading version info of installed patcher.
[INFO]     Tue Aug 31 21:23:43 2021 - Parsing version info to number -  "7"
[INFO]     Tue Aug 31 21:23:43 2021 - Local patcher id -  "9f3a9c9489b3a6b4d929b5e213b2"
[INFO]     Tue Aug 31 21:23:43 2021 - Local version - 7
[INFO]     Tue Aug 31 21:23:43 2021 - Latest version is already installed
[INFO]     Tue Aug 31 21:23:43 2021 - Starting patcher.
[INFO]     Tue Aug 31 21:23:43 2021 - Reading patcher manifest.
[DEBUG]    Tue Aug 31 21:23:43 2021 - Preparing execute target:  "C:/Program Files (x86)/Nin Online Inochi/patcher/Hitspark Launcher.exe"  with arguments:  ("--installdir", "C:/Program Files (x86)/Nin Online Inochi/app", "--lockfile", "C:/Program Files (x86)/Nin Online Inochi/.lock", "--secret", "N/+T/zX/kf+d/zv/m/+X/zX/Of85/zf/O/+d/5v/Nf+d/zv/mf+N/4//m/8z/5X/Of81/5H/kf87/zf/nf+f/w==", "--online")
[INFO]     Tue Aug 31 21:23:43 2021 - Unlocking the lock file.
[INFO]     Tue Aug 31 21:23:43 2021 - Launcher has finished successfully
[INFO]     Tue Aug 31 21:23:43 2021 - Close window request.
[INFO]     Tue Aug 31 21:23:43 2021 - Allowing the window to be closed.
</details>

**Comment by Seitenchi** [comment]
Added log from patcher log dunno if it helps.

**Comment by Seitenchi** [comment]
I seem to have found a solution. in order to get the client working I had to go to control panel, then to uninstall a program, then check under.net4.8 and enable asp .net. After doing this the game launches correctly. https://gyazo.com/ce781ebcc4a7f994b0cb1e188047b37b

**Comment by RorySoh** [comment]
Thank you for presenting us with your solution, we will incorporate it into our Troubleshoot!
Appreciate it.
