### ISSUE TITLE
Crashing on Login

### ISSUE THREAD

**Issue by StillQuips** [HitsparkInteractive/NinOnline#85]
## Problem description

I can no longer log into the game, upon authorizing login and clicking on the server the screen will go black for a few seconds before closing the game.

## Steps to reproduce issue

1. I can't find a reliable way to guarantee the crash however on every account that's been affected with this bug (Three so far), it's crashed during mapswitch.

## Observed result

Video of the bug occuring can be watched here: https://vimeo.com/613025858

## More details

**Affected Client Version:** 

Bug occurs on Inochi Client, sadly can't specify when the bug started to occur as I only returned recently.

## Error Logs

<details><summary>View details</summary>

The following error occured 'Could not load file or assembly 'CefSharp.Core.Runtime, Version=93.1.111.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' or one of its dependencies. An attempt was made to load a program with an incorrect format.' at '   at CefSharp.Cef.Shutdown()
   at l589FA7GIrYRuXmapVO.bHr9ih3e7(l589FA7GIrYRuXmapVO )
   at client.modGeneral.DestroyGame() in D:\NinOnlineSrc\Core\ninonline-c-client\modGeneral.cs:line 488
   at client.modInput.KeN1PZTQ8ZaGdARxLSS()
   at client.modInput.ExitTheGame_MouseUp(Int32 X, Int32 Y) in D:\NinOnlineSrc\Core\ninonline-c-client\modInput.cs:line 6953
   at client.modInput.obt6pkGuYlWlMJCFr3Y(Int32 X, Int32 Y)
   at client.modInput.HandleMainMouseUp(Int32 X, Int32 Y, Button Button) in D:\NinOnlineSrc\Core\ninonline-c-client\modInput.cs:line 3859
   at client.SFMLGameWindow.GameWindowForm_MouseReleased(Object sender, MouseButtonEventArgs e) in D:\NinOnlineSrc\Core\ninonline-c-client\Rendering\SFMLGameWindow.cs:line 386
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at SFML.Window.Window.CallEventHandler(Event e)
   at SFML.Window.Window.DispatchEvents()
   at b8igLn2sqhjtefXr4G.bHr9ih3e7(Object , b8igLn2sqhjtefXr4G )
   at client.modGameLogic.MainLoop() in D:\NinOnlineSrc\Core\ninonline-c-client\modGameLogic.cs:line 4213'.

[errors.txt](https://github.com/HitsparkInteractive/NinOnline/files/7220956/errors.txt)

</details>

**Comment by RorySoh** [comment]
@michaelsakharov

**Comment by RorySoh** [comment]
This will likely be fixed in the next update
